### ISSUE TITLE
Instrumentation of "(`B, _) | (_, `B)" pattern breaks typing

### ISSUE THREAD

**Issue by monate** [aantron/bisect_ppx#358]
Hello,
The example quoted below can be compiled with `ocamlfind opt  -c bisect_bug1.ml` but does not type with bisect_pxx 2.5.0/OCaml 4.11.1:
```OCaml
type t = [ `A | `B ]
module M: sig
  val f: [< t] -> [> t ]
end =
  struct
    let f m =
      match m, m with
      | `A, `A -> `A
      | `B, _ | _, `B -> `B
  end
```
Here is the error:
```Console
$ ocamlfind opt -package bisect_ppx -c bisect_bug1.ml
File "bisect_bug1.ml", lines 5-10, characters 2-5:
 5 | ..struct
 6 |     let f m =
 7 |       match m, m with
 8 |       | `A, `A -> `A
 9 |       | `B, _ | _, `B -> `B
10 |   end
Error: Signature mismatch:
       Modules do not match:
         sig val f : [< `A | `B > `B ] -> [> `A | `B ] end
       is not included in
         sig val f : [< t ] -> [> t ] end
       Values do not match:
         val f : [< `A | `B > `B ] -> [> `A | `B ]
       is not included in
         val f : [< t ] -> [> t ]
       File "bisect_bug1.ml", line 3, characters 2-24: Expected declaration
       File "bisect_bug1.ml", line 6, characters 8-9: Actual declaration
```
Note that this seems related to the or-pattern because expanding line 9 into 
```OCaml
    | `B, _ -> `B 
    | _, `B -> `B
```
leads to a typeable program.

Thanks for providing such a useful tool!

**Comment by mbouaziz** [comment]
Is it fixed in the dev version?

**Comment by monate** [comment]
Indeed, this looks closely related: I will try to compile the dev version to check if my example is now ok. Thanks for the feedback!

**Comment by monate** [comment]
Thanks for providing the proper opam pin invocation.
The bug is sadly still present in the dev version.

**Comment by aantron** [comment]
@monate I will look into this shortly.

@monate, @mbouaziz, #327 will land shortly, and port Bisect_ppx to ppxlib. At that point,

1. Bisect_ppx will require OCaml 4.04.1 (currently requires 4.02.3).
2. Bisect_ppx will require ppxlib and ocaml-migrate-parsetree >= 2 (currently requires < 2).

The latter change, in particular, makes Bisect_ppx incompatible with switches that use any PPXs that haven't yet been ported to ppxlib and/or OMP 2.

Will you need a release of Bisect_ppx with recent bugfixes but without the ppxlib port?

**Comment by aantron** [comment]
So far, I seem to have simplified the example down to this, a standalone program completely outside the Bisect context:

```ocaml
type t = [ `A  | `B ]

module M :
sig
  val f : [< t ] -> unit
end =
struct
  let f v =
    match (v, v) with
    | `A, `A -> ()
    | `B, _ | _, `B as x -> ()
end
```

Removing the `as x` makes the program typecheck. The `as x` simulates part of the instrumentation that is added by Bisect in order to determine which subpattern was actually matched. I don't know (yet) why exactly this triggers inferring the `` > `B `` or if there is a nice way to work around it.

@monate I replaced `_` by `#t` and your original example compiled with Bisect, as well as standalone with an extra `as x`:

```ocaml
type t = [ `A | `B ]
module M: sig
  val f: [< t] -> [> t ]
end =
  struct
    let f m =
      match m, m with
      | `A, `A -> `A
      | `B, #t | #t, `B -> `B
  end
```

i.e. this variant "survives" decoration with an `as`-binding. Is it practical for you to try something analogous in your real code?

While I haven't fully explored the issue, the set of other things I tried (and failed with) make me suspect this issue might not be fully or at all solvable in Bisect_ppx.

It might (agreeing with @mbouaziz) be related to #325. cc @gasche, in case you recognize something here.

**Comment by aantron** [comment]
Among other things, I tried having Bisect emit the main instrumentation for or-patterns here. A standalone version of it is

```ocaml
  module Bisect_visit___test___ml =
    struct
      let ___bisect_visit___ = ignore
      let ___bisect_post_visit___ point_index result =
        ___bisect_visit___ point_index; result
    end
  open Bisect_visit___test___ml
  [@@@ocaml.text "/*"]
  type t = [ `A  | `B ]
  module M : sig val f : [< t] -> [> t] end =
    struct
      let f : [< t] -> [> t] =
        fun v ->
          ___bisect_visit___ 3;
          (match (v, v) with
           | ___bisect_matched_value___ ->
               (match ___bisect_matched_value___ with
                | (`A, `A) -> (___bisect_visit___ 0; `A)
                | (`B, _)|(_, `B) ->
                    (
                      (((match ___bisect_matched_value___ with
                        | (`B, _) -> (___bisect_visit___ 1; ())
                        | (_, `B) -> (___bisect_visit___ 2; ())
                        | _ -> ()))
                     [@ocaml.warning "-4-8-9-11-26-27-28-33"]);
                     `B)))
    end
```

(sorry, it's slightly ugly, it's `-dsource` output). It appears that just having the outer binding to `___bisect_matched_value___` is enough to have the typechecker require `` > `B ``, even if the nested match is commented out. That outer binding is the equivalent to the `as` in this style of instrumentation.

**Comment by monate** [comment]
> 1. Bisect_ppx will require OCaml 4.04.1 (currently requires 4.02.3).
> 2. Bisect_ppx will require ppxlib and ocaml-migrate-parsetree >= 2 (currently requires < 2).
> 
> The latter change, in particular, makes Bisect_ppx incompatible with switches that use any PPXs that haven't yet been ported to ppxlib and/or OMP 2.
> 
> Will you need a release of Bisect_ppx with recent bugfixes but without the ppxlib port?

I confirm that upgrading these dependencies is not a problem for me.

**Comment by gasche** [comment]
Regarding the typing issue, I created an upstream issue at https://github.com/ocaml/ocaml/issues/10193 . Thanks!

**Comment by aantron** [comment]
I managed to "fix" the "main" instrumentation from my second big comment by inserting `Obj.magic` into the `match`. However, I am extremely hesitant to use that, because I think it will interfere with type-directed record field and/or constructor disambiguation inside the nested `match`, which is likely to be much more frequently needed than this kind of nested polymorphic variant inside or-patterns. I suspect it will have other drawbacks, too.

The current "main" instrumentation is itself a workaround for (as I understand it) broken `as` typing found by @mbouaziz in #325.

@gasche thanks for the upstream issue.

**Comment by monate** [comment]
> i.e. this variant "survives" decoration with an `as`-binding. Is it practical for you to try something analogous in your real code?

I will try this on the real code. So far I have the simple workaround of expanding the or-pattern into 2 patterns (at the cost of duplicating the code)

**Comment by aantron** [comment]
I'm closing this for now as a sort of "cantfix." I haven't been able to find a way to fix/work around this on the Bisect side. There are at least two workarounds that the user can try:

- Split up the case.
- Use `#t` instead of `_`.

And there is the possibility of adding some kind of `[@coverage magic]` annotation in the future, that will insert `Obj.magic` into the instrumentation. That might be useful to avoid typing issues where nothing else can reasonably help.
